<?php

// Generated by `php artisan lang:translate fr` from lang/en/auth.php.
// Edit freely — a re-run only fills keys that are missing, unless --force.

return [
    'failed' => 'Ces informations d\'identification ne correspondent pas à nos dossiers.',
    'password' => 'Le mot de passe fourni est incorrect.',
    'throttle' => 'Trop de tentatives de connexion. Veuillez réessayer dans :seconds secondes.',
];
