<?php

// Generated by `php artisan lang:translate es` from lang/en/auth.php.
// Edit freely — a re-run only fills keys that are missing, unless --force.

return [
    'failed' => 'Estas credenciales no coinciden con nuestros registros.',
    'password' => 'La contraseña proporcionada es incorrecta.',
    'throttle' => 'Demasiados intentos de inicio de sesión. Inténtalo de nuevo en :seconds segundos.',
];
