<?php

// Generated by `php artisan lang:translate es` from lang/en/passwords.php.
// Edit freely — a re-run only fills keys that are missing, unless --force.

return [
    'reset' => 'Su contraseña ha sido restablecida.',
    'sent' => 'Le hemos enviado por correo electrónico el enlace para restablecer su contraseña.',
    'throttled' => 'Espere antes de volver a intentarlo.',
    'token' => 'Este token de restablecimiento de contraseña no es válido.',
    'user' => 'No podemos encontrar un usuario con esa dirección de correo electrónico.',
];
