<?php

return [
    'title' => null,
    'subtitle' => null,
    'title-print-alternative' => null,
    'show-title' => true,

    'metadata' => [
        'title' => null,
        'description' => null,
        'key' => null,
        'image' => null,
        'type' => 'site',
        'url' => null,
    ],

    // STATUS COLOR MAPPING

    'status-color-map' => [
        // SUCCESS
        'delivered' => 'success',
        'confirmed' => 'success',
        'verified' => 'success',
        'active' => 'success',
        'on' => 'success',
        'success' => 'success',
        'accepted' => 'success',
        'paid' => 'success',
        'approved' => 'success',
        'closed' => 'success',
        'cleared' => 'success',
        'used' => 'success',
        'passed' => 'success',
        'showing' => 'success',
        'seen' => 'success',
        'successful' => 'success',
        'resolved' => 'success',
        'connected' => 'success',
        'yes' => 'success',
        'ongoing' => 'success',
        'published' => 'success',
        'completed' => 'success',
        'present' => 'success',
        // DANGER
        'canceled' => 'danger',
        'cancelled' => 'danger',
        'revoked' => 'danger',
        'blocked' => 'danger',
        'failed' => 'danger',
        'deleted' => 'danger',
        'locked' => 'danger',
        'turned-off' => 'danger',
        'admin-lock' => 'danger',
        'debit' => 'danger',
        'expired' => 'danger',
        'retry' => 'danger',
        'rejected' => 'danger',
        'banned' => 'danger',
        'no' => 'danger',
        'absent' => 'danger',
        // WARNING
        'pending' => 'warning',
        'queued' => 'warning',
        'claim' => 'warning',
        'not-published' => 'warning',
        'verification' => 'warning',
        'waiting' => 'warning',
        'unused' => 'warning',
        'scheduled' => 'warning',
        'paused' => 'warning',
        'incomplete' => 'warning',
        'late' => 'warning',
        'draft' => 'warning',
        'pending-deletion' => 'warning',
        // PRIMARY
        'created' => 'primary',
        'archived' => 'primary',
        'not-seen' => 'primary',
        'verify' => 'primary',
        'review' => 'primary',
        'not-activated' => 'primary',
        'not-active' => 'primary',
    ],
];
